CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID PRIMARY KEY,
    "user_name" VARCHAR(50) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);